//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9_BurgerPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculatingCost
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public string UnitOfMeasurement { get; set; }
        public double Quantity { get; set; }
        public double Cost { get; set; }
        public double Total { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
