//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9_BurgerPlus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBurgerPlusEntities : DbContext
    {

        private static DBBurgerPlusEntities _context;
        public static DBBurgerPlusEntities GetContext()
        {
            if (_context == null)
                _context = new DBBurgerPlusEntities();
            return _context;
        }
            public DBBurgerPlusEntities()
            : base("name=DBBurgerPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalculatingCost> CalculatingCost { get; set; }
        public virtual DbSet<Costs> Costs { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Сustomers> Сustomers { get; set; }
        public virtual DbSet<СustomersOrder> СustomersOrder { get; set; }
    }
}
