//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9_BurgerPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class СustomersOrder
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public int Quantity { get; set; }
        public string UnitOfMeasurement { get; set; }
        public int Cost { get; set; }
        public int Summa { get; set; }
        public int Customer { get; set; }
        public int User { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
        public virtual Сustomers Сustomers { get; set; }
    }
}
