//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9_BurgerPlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сustomers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сustomers()
        {
            this.СustomersOrder = new HashSet<СustomersOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Inn { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public bool Saleman { get; set; }
        public bool Buyer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СustomersOrder> СustomersOrder { get; set; }
    }
}
